name: g_w_community
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.5.3+53

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  assets_audio_player: 
    git:
      url: https://github.com/FlutterFlow/Flutter-AssetsAudioPlayer.git
      ref: 243f9533279b73fa9dae345cc96e5d7d84cac0ac
  assets_audio_player_web: 
    git:
      url: https://github.com/FlutterFlow/Flutter-AssetsAudioPlayerWeb.git
      ref: cae7ceb6af99f4da1ec27136d312d0ef045c83d9
  audio_service:
  audio_session:
  auto_size_text: 3.0.0
  blurhash_dart: 1.2.1
  cached_network_image: 3.4.1
  collection: 1.19.1
  dropdown_button2: 2.3.9
  easy_debounce: ^2.0.3
  equatable: 2.0.7
  file_picker: ^10.3.7
  firebase_analytics: ^12.0.4
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.5
  flutter_animate: ^4.5.2
  flutter_html: 3.0.0
  flutter_spinkit: ^5.2.2
  font_awesome_flutter: ^10.12.0
  from_css_color: 2.0.0
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  google_sign_in: ^7.2.0
  http: 1.4.0
  image: ^4.5.4
  image_picker: ^1.2.1
  internet_file: ^1.3.0
  intl: 0.20.2
  json_path: ^0.8.0
  just_audio:
  just_audio_background:
  lottie: ^3.3.2
  mask_text_input_formatter: 2.9.0
  mime_type: ^1.0.1
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  pdfx: 2.9.2
  provider: ^6.1.5+1
  rive: ^0.13.20
  rxdart: 0.27.7
  shared_preferences: 2.5.3
  smooth_page_indicator: ^1.2.1
  sticky_headers: 0.3.0+2
  supabase: ^2.10.0
  supabase_flutter: ^2.10.3
  timeago: 3.7.1
  url_launcher: ^6.3.2
  video_player: ^2.10.1
  webviewx_plus: 
    git:
      url: https://github.com/FlutterFlow/webviewx_plus.git
      ref: 4f84ece5e06d52643c5d844f41880baf8440c584
  youtube_player_iframe: 5.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  http_parser: any
dependency_overrides:
  device_info_plus: 11.5.0
  device_info_plus_platform_interface: 7.0.3
  http: 1.4.0
  rxdart: 0.27.7
dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/

  fonts:
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
